### ISSUE TITLE
Cannot set screenID and "Multiple screens" at the same time

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#2]
In the settings, when entering a screenID and checking "Multiple screens", the system will only process the Multi Screen check. When opening the dialog again, screenID is empty. When the screenID is entered again, it is properly stored. Likewise if you only enter the ID without clicking Multiple, the screenID is stored on the first attempt.

**Comment by jplangst** [comment]
This issue appeared after changing to functional component. Perhaps you could investigate @michaelhil
