### ISSUE TITLE
Create observer messages at source and pass them as event.observerMessage

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#23]
To simplify the processing in the observer module, we generate the observer message as a complete string at the source (button, image, etc) and pass it through the log object/mqtt. 

Perhaps we should pass the observer message to makeLogObject.js (currently called messageUtils.js) as an argument, e.g. makeLogObject(other argument, other argument, observerMessage)

Suggestion for the messages for the Button type:
Assume a component that asks "Which fruit do you like?" with APPLES, ORANGES, BANANAS as buttons.
When Oranges is clicked, we want the message "ORANGES (Which fruit do you like?)"
When Bananas is clicked, we want the message "BANANAS (Which fruit do you like?)"
When Bananas is un-clicked, we want the message "Un-clicked BANANAS (Which fruit do you like?)"
Assuming the user has clicked Oranges and Bananas, when the user clicks NEXT, we want to use responsesArray to generate the message "Final answer: BANANAS, ORANGES (Which fruit do you like?)"

If a component has a Correct Answer defined, then the observer message should show if the answer was correct and what the correct answer was, e.g.
"CORRECT - SG1, SG2 (Which Steam Generators are above 50%? Answer: SG1, SG2)" or
"INCORRECT - SG1, SG2, SG3 (Which Steam Generators are above 50%? Answer: SG1, SG2)"

**Comment by tailyer** [comment]
Done for {Button, Text, Number} component. Observer also shows logs for those components.
Technical note: in useEffect cleanup function, the state will be reset to the initial values, therefore can not access the latest state's value in the clean-up. Use useRef to store the state value in the clean-up function (https://github.com/facebook/react/issues/14066)

Image component is logged. The log structure on the observer should be discussed further.
