### ISSUE TITLE
Record event times as timestamps instead of formatted times

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#24]
In makeLogObject.js (messageUtils), we should log all event times as raw timestamps, i.e. Date.now(), instead of formatted time (at the moment: sessionStartTime: playerUtils.getFormattedCurrentTime()). This makes it easier to calculate reaction times, and we can always format it later if needed.

**Comment by tailyer** [comment]
Fixed! Change the getFormattedTime to getCurrentTime.
