### ISSUE TITLE
Move message sending higher up to component hierarchy

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#25]
We currently send button-level messages directly from buttonElement.js. I am concerned that this might cause some performance issues as every button will create its own connection to the broker, and later on its own database connection. We should therefore move the dispatch of messages higher-up, e.g. to the level of button/index.js. That way it will be only one mqtt connection per component. We pass a callback function via props from index.js to buttonElement.js that ButtonElement.js can use to pass the information that it was clicked.

**Comment by tailyer** [comment]
Done! The button element (single button) now is used only for displaying content. All the mqtt sender will be handle in the parent's level, a.k.a ButtonComponent.
