### ISSUE TITLE
Generate a screen uid when Synquesticon is launched in a tab

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#26]
We currently have a screen id (screen name) that is defined through the settings or through buttons. However if the user doesn't set one, or sets the same on multiple tabs/screens, we have no way to distinguish them. We should have a unique id for every instance of Synquesticon. This uid will be logged as context.screen.uid.

We alread have uuid unstalled (import uuid from 'react-uuid') and can generate a uuid simply through uuid(). We should generate this somewhere high up in the component tree so it is called when Synquesticon is loaded or re-loaded. We can store it through Window.sessionStorage or some similar mechanism, so that it is accessible to makeLogObject() and other functions.

**Comment by tailyer** [comment]
uuid is added and stored in Redux store.
