### ISSUE TITLE
Clicks on image

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#27]
When an image component is set to "clickable", we want to record every click on that image. We need two types of data:
(1) A list x-y coordinates for each click. Those should be relative coordinates (i.e. 0-1) and they should relate to the image, not to the screen or viewport. If it is not too much work, the list of coordinates should also include any AOIs for that link. 
Example:
coordinateLog = [ [0.231, 0.782, "AOI3, AOI6"], [0.491, 0.140, "AOI2"], [0.331, 0.955, ""], etc ]

(2) An array AOIcount that records how many clicks have been made on each AOI. It should also include one field for any clicks that were not on an AOI ("Background). We may need a separate array for the AOI names. Example for a component with 5 AOIs:
AOInames = [ "AOI1", "AOI2", "AOI3", "AOI4", "AOI5", "Background"]
AOIcount = [0, 2, 6, 0, 1, 8]

Alternatively, they could be combined:
AOIcount = [ ["AOI1", 0], ["AOI2", 2], ["AOI3, 6], etc]

**Comment by tailyer** [comment]
Done and logged on Observer
