### ISSUE TITLE
Display and stream motion data

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#29]
We want to be able to collect and tag various sensor data sources through Synquesticon. As a test we can start with motion data from mobile devices (gyro/accelerometer) using the Web Sensor API.

For quick development, you can just implement that on the Instruction component for now.
(1) Show all available motion data as numerical values on a web page (Instruction page). Also show updates.
(2) Stream data out via mqtt. What format should the data object for motion data have?

**Comment by tailyer** [comment]
(1) add an event listener to listen the sensor data. Those are shown: acceleration coordinates (x, y and z) and rotation rates (alpha, beta, gamma)
(2) Can be a header eventType "SENSOR_INFO" and acceleration coordinates
For example 
sensor_object = {
eventType: SENSOR_INFO",
acce_x: 0.1,
acce_y: 0.1,
acce_z: 0.1,
rot_a: 15,
rot_b: 15,
rot_g: 15
}
