### ISSUE TITLE
Does not record overlapping AOIs

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#3]
You can define overlapping AOIs so that a point on an image can "belong" to multiple AOIs. However the logs only show one AOI. Could we show all AOIs for the click-point as a comma-separated list?

![image](https://user-images.githubusercontent.com/64902743/81415687-0cb43c00-9149-11ea-8340-24b51e6360d4.png)

**Comment by jplangst** [comment]
Fixed
