### ISSUE TITLE
Migration to cloud: Phase 1 + 2

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#36]
To make Synquesticon easier to manage, we want to start using Docker and cloud services. We agreed to migrate to Azure App Services. The first phase covers setting up the Azure environment, subscribing to the right services, packaging some part of the Synquesticon deployment in docker, and deploying it on Azure. Steps:

**- Set up Azure so that we have a web server address and ssl certificate.**
**- Determine the order in which we should deploy things. I suggest the following order for Phase 1:**

- (1) MQTT broker. Since we are not tied to Node any more, we should use mosquitto 
https://hub.docker.com/_/eclipse-mosquitto
Let's get this running under Azure with a secure certificate.

- (2) MongoDB. Once we have this running, we can point our syn.ife server or local installation to it for testing.
https://hub.docker.com/_/mongo 
How can we make configuration changes to mongoDB? 
Another issue to explore is how we could run multiple separate instances of mongoDB so that separate users / user groups can have their own, fully self-contained database (thinking about supplying Synquesticon as a service in the future)

- (3) MQTTmotionLogger.js. Deploy this as a separate mini-service, connected either to the DB on Azure. We should modify it so it can also receive eye tracking data.

- (4) ML classifier. We use the same architecture as now (a Node program listening to mqtt sensor messages and returning classification objects via mqtt). We should look into an easy process for uploading new versions of TF models and switching between TF models. We should also make this work for eye tracking data. Perhaps we can abstract it in some way so it will work for any kind of data/model?

The migration of the Synquesticon code itself will come in Phase 2 (perhaps we can make separate docker images for the backend and frontend?)

**Comment by tailyer** [comment]
- Synquesticon (frontend + backend) and aedes broker are deployed using:

1. + Reverse proxy based on nginx
2. + Docker compose with docker containers (1 node image for Frontend, 1 nginx image for reverse proxy, 1 node for Backend)
3. + Azure web app
4. + Azure Cosmos DB with MongoDB

- ML classifier is deployed as a separate App service for now as it requires further training to improve models' output.
- MQTT motion logger will be integrated in to Docker compose of the 1st point

**Comment by tailyer** [comment]
MQTT motion logger has been integrated in Synquesticon.
Technical hint: can be deployed as Web Jobs later (if Azure later supports Web Jobs for Linux-based containers on Web Apps service.)
