### ISSUE TITLE
FEATURE: Set screenID through buttons

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#4]
This feature helps users set screenID more easily and enables screenID for users who receive an experiment through URL (they can't currently set screenID). The modification is simple:
- The screenID can be be set through the button component. The experimenter makes a task with a set of buttons corresponding to the different screenIDs needed in the experiment.
- The experimenter labels this task with the tag "setScreenID".
- When "Next" is clicked, we check if the tags for this task contain "setScreenID". If so, the screenID is set to the value of the button that was pressed, and we set "multiple screens" to on.

**Comment by jplangst** [comment]
This feature has now been added. 

In order for link shared experiments to function with this as well modifications were made to the url that is created.

Once a link share is clicked a participant object will be created in the database and it's id will be appended to the url. To start a multiple screen experiment the same link should be used for all browsers. 
NB! Do not generate more links as they will then create new participants. One link should be used per participant. 
NB! Do not reuse the same link for more than one participant!
