### ISSUE TITLE
FEATURE: Hide "Next" button

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#5]
We need to be able to hide the Next/Skip button on screens. We can't do it on the Task level, as the "hide" needs to be screen-specific. The easiest option is to add an option "Hide next" to every component. If "Hide next" is turned on for any component on a particular screen, we hide the Next button for this screen. That way we can have only one Next button in a multi-screen setup, and control perfectly where the Next button is shown.

**Comment by jplangst** [comment]
Another option could be to add a checkbox in the device settings to assign one screen to have the next buttons. Then you don't have to add this to all the components. Unless there is some compelling reason to have the next button on different screens at different times.

**Comment by jplangst** [comment]
Finished this feature. Checkboxes have been added to the individual components. It will only be used if multiple screens has been enabled.
